In [14]:
import pandas as pd

In [15]:
ds = pd.read_csv('ds_diabetes.csv')

In [16]:
ds

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [17]:
ds.describe()
pd.unique(ds['diabetes'])

array([0, 1], dtype=int64)

In [18]:
ds['diabetes'].value_counts()

diabetes
0    91500
1     8500
Name: count, dtype: int64

In [19]:
x= ds.drop(columns='diabetes', axis=1)
y= ds['diabetes']

from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

x['gender'] = le.fit_transform(x['gender'])
x['smoking_history'] = le.fit_transform(x['smoking_history'])

x

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,0,80.0,0,1,4,25.19,6.6,140
1,0,54.0,0,0,0,27.32,6.6,80
2,1,28.0,0,0,4,27.32,5.7,158
3,0,36.0,0,0,1,23.45,5.0,155
4,1,76.0,1,1,1,20.14,4.8,155
...,...,...,...,...,...,...,...,...
99995,0,80.0,0,0,0,27.32,6.2,90
99996,0,2.0,0,0,0,17.37,6.5,100
99997,1,66.0,0,0,3,27.83,5.7,155
99998,0,24.0,0,0,4,35.42,4.0,100
99999,0,57.0,0,0,1,22.43,6.6,90

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.2 , random_state=99)

In [21]:
from sklearn.tree import DecisionTreeClassifier 
tree= DecisionTreeClassifier(criterion='entropy')
tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [22]:
y_prediksi = tree.predict(x_test)
y_prediksi

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score
print("Nilai Akurasi", accuracy_score(y_test,y_prediksi))

Nilai Akurasi 0.95355

In [24]:
databaru = pd.read_excel('db_diabetes.xlsx')
newdata = databaru.iloc[:,:]
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
newdata['gender'] = le.fit_transform(newdata['gender'])
newdata['smoking_history'] = le.fit_transform(newdata['smoking_history'])

newprediksi = tree.predict(newdata)
print("Hasil prediksi: \n")
for i, prediksi in enumerate(newprediksi,start=1):
    tree = "Diabetes" if prediksi == 1 else "Tidak Diabetes"
    newdata_baris= newdata.iloc[i-1]
    print(f"Data uji ke- {i}: {newdata_baris.tolist()} = \"{tree}\"")

Hasil prediksi:

Data uji ke- 1: [0.0, 46.0, 0.0, 1.0, 3.0, 25.19, 6.1, 155.0] = "Diabetes"
Data uji ke- 2: [0.0, 67.0, 1.0, 1.0, 2.0, 27.32, 6.5, 200.0] = "Tidak Diabetes"
Data uji ke- 3: [0.0, 44.0, 0.0, 0.0, 2.0, 15.94, 5.8, 145.0] = "Tidak Diabetes"
Data uji ke- 4: [1.0, 21.0, 0.0, 1.0, 0.0, 15.8, 6.2, 126.0] = "Tidak Diabetes"
Data uji ke- 5: [1.0, 30.0, 0.0, 0.0, 2.0, 27.01, 6.0, 100.0] = "Tidak Diabetes"
Data uji ke- 6: [0.0, 59.0, 0.0, 1.0, 2.0, 27.32, 6.6, 85.0] = "Tidak Diabetes"
Data uji ke- 7: [0.0, 27.0, 1.0, 0.0, 1.0, 22.19, 6.2, 85.0] = "Tidak Diabetes"
Data uji ke- 8: [0.0, 59.0, 0.0, 1.0, 0.0, 27.45, 5.7, 130.0] = "Tidak Diabetes"
Data uji ke- 9: [1.0, 19.0, 0.0, 0.0, 0.0, 17.98, 5.0, 200.0] = "Tidak Diabetes"
Data uji ke- 10: [1.0, 13.0, 0.0, 1.0, 1.0, 27.32, 6.5, 260.0] = "Diabetes"
Data uji ke- 11: [0.0, 56.0, 0.0, 0.0, 2.0, 27.32, 7.5, 200.0] = "Diabetes"
Data uji ke- 12: [1.0, 2.0, 0.0, 1.0, 0.0, 54.7, 6.1, 160.0] = "Tidak Diabetes"
Data uji ke- 13: [0.0, 7.0, 0.0, 0.0, 2.0, 36.05, 6.2, 130.0] = "Tidak Diabetes"
Data uji ke- 14: [0.0, 3.0, 1.0, 0.0, 2.0, 25.69, 6.1, 159.0] = "Tidak Diabetes"
Data uji ke- 15: [0.0, 30.0, 0.0, 1.0, 0.0, 27.32, 6.0, 160.0] = "Tidak Diabetes"